-- MySQL Script generated by MySQL Workbench
-- Thu May 27 14:43:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sql10399086
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql10399086
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql10399086` DEFAULT CHARACTER SET utf8 ;
USE `sql10399086` ;
-- -----------------------------------------------------
-- Table `sql10399086`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `sql10399086`.`Barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Barrio` (
  `codBarrio` INT NOT NULL AUTO_INCREMENT,
  `nombreBarrio` VARCHAR(45) NULL,
  PRIMARY KEY (`codBarrio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Usuario` (
  `idUsuario` VARCHAR(20) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `apellidoUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `contraseñaUsuario` VARCHAR(45) NOT NULL,
  `telefonoUsuario` VARCHAR(45) NOT NULL,
  `fechaNacUsuario` DATE NOT NULL,
  `totalMonedaUsuario` BIGINT(50) NOT NULL,
  `direccion` VARCHAR(75) NOT NULL,
  `estadoReferido` BIGINT NOT NULL,
  `Barrio_codBarrio` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Barrio1_idx` (`Barrio_codBarrio` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Barrio1`
    FOREIGN KEY (`Barrio_codBarrio`)
    REFERENCES `sql10399086`.`Barrio` (`codBarrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Oferta` (
  `codOferta` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(15) NOT NULL,
  `nombreOferta` VARCHAR(45) NOT NULL,
  `descripcionOferta` VARCHAR(255) NOT NULL,
  `precioOferta` BIGINT(45) NOT NULL,
  `estadoOferta` TINYINT NOT NULL,
  `lugarServicio` VARCHAR(45) NULL,
  `imagenProducto` VARCHAR(345) NULL,
  `cantidadProducto` INT NULL,
  `Usuario_idUsuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codOferta`),
  INDEX `fk_Oferta_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Oferta_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sql10399086`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`EstadoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`EstadoCompra` (
  `codEstadoCompra` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codEstadoCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Compra` (
  `codCompra` INT NOT NULL AUTO_INCREMENT,
  `ofertaCambio` INT NULL,
  `precioCompra` BIGINT(45) NULL,
  `fechaEnvio` DATE NULL,
  `Oferta_codOferta` INT NOT NULL,
  `Usuario_idUsuario` VARCHAR(20) NOT NULL,
  `EstadoCompra_codEstadoCompra` INT NOT NULL,
  PRIMARY KEY (`codCompra`),
  INDEX `fk_Compra_Oferta1_idx` (`Oferta_codOferta` ASC) VISIBLE,
  INDEX `fk_Compra_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Compra_EstadoCompra1_idx` (`EstadoCompra_codEstadoCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Oferta1`
    FOREIGN KEY (`Oferta_codOferta`)
    REFERENCES `sql10399086`.`Oferta` (`codOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sql10399086`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_EstadoCompra1`
    FOREIGN KEY (`EstadoCompra_codEstadoCompra`)
    REFERENCES `sql10399086`.`EstadoCompra` (`codEstadoCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Transaccion` (
  `codTransaccion` INT NOT NULL AUTO_INCREMENT,
  `conceptoTransaccion` VARCHAR(45) NOT NULL,
  `valorTransaccion` BIGINT(55) NOT NULL,
  `estadoTransaccion` TINYINT NOT NULL,
  `Usuario_idUsuario` VARCHAR(20) NOT NULL,
  `Compra_codCompra` INT NULL,
  PRIMARY KEY (`codTransaccion`),
  INDEX `fk_Transaccion_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Transaccion_Compra1_idx` (`Compra_codCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Transaccion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sql10399086`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaccion_Compra1`
    FOREIGN KEY (`Compra_codCompra`)
    REFERENCES `sql10399086`.`Compra` (`codCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Comentario` (
  `codComentario` INT NOT NULL AUTO_INCREMENT,
  `descripcionComentario` VARCHAR(345) NOT NULL,
  `horaComentario` TIME NOT NULL,
  `respuestaComentario` VARCHAR(345) NULL,
  `Oferta_codOferta` INT NOT NULL,
  `Usuario_idUsuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codComentario`),
  INDEX `fk_Comentario_Oferta1_idx` (`Oferta_codOferta` ASC) VISIBLE,
  INDEX `fk_Comentario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Oferta1`
    FOREIGN KEY (`Oferta_codOferta`)
    REFERENCES `sql10399086`.`Oferta` (`codOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sql10399086`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Valoracion` (
  `codValoracion` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `Oferta_codOferta` INT NOT NULL,
  PRIMARY KEY (`codValoracion`),
  INDEX `fk_Valoracion_Oferta1_idx` (`Oferta_codOferta` ASC) VISIBLE,
  CONSTRAINT `fk_Valoracion_Oferta1`
    FOREIGN KEY (`Oferta_codOferta`)
    REFERENCES `sql10399086`.`Oferta` (`codOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Referido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Referido` (
  `codReferido` VARCHAR(50) NOT NULL,
  `valorReferido` INT NOT NULL,
  `Usuario_idUsuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codReferido`),
  INDEX `fk_Referido_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Referido_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sql10399086`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Mensaje` (
  `codMensaje` INT NOT NULL AUTO_INCREMENT,
  `desMensaje` VARCHAR(345) NOT NULL,
  `destinatario` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` VARCHAR(20) NOT NULL,
  `Compra_codCompra` INT NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codMensaje`),
  INDEX `fk_Mensaje_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Mensaje_Compra1_idx` (`Compra_codCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Mensaje_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sql10399086`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Compra1`
    FOREIGN KEY (`Compra_codCompra`)
    REFERENCES `sql10399086`.`Compra` (`codCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10399086`.`Reclamación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10399086`.`Reclamacion` (
  `codReclamación` INT NOT NULL AUTO_INCREMENT,
  `desReclamacion` VARCHAR(345) NOT NULL,
  `imagenReclamacion` BLOB NULL,
  `Compra_codCompra` INT NOT NULL,
  `estadoReclamacion` TINYINT NOT NULL,
  PRIMARY KEY (`codReclamación`),
  INDEX `fk_Reclamación_Compra1_idx` (`Compra_codCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Reclamación_Compra1`
    FOREIGN KEY (`Compra_codCompra`)
    REFERENCES `sql10399086`.`Compra` (`codCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE Oferta AUTO_INCREMENT=1;
ALTER TABLE Compra AUTO_INCREMENT=1;
ALTER TABLE Transaccion AUTO_INCREMENT=1;
ALTER TABLE Comentario AUTO_INCREMENT=1;
ALTER TABLE Valoracion AUTO_INCREMENT=1;
ALTER TABLE Barrio AUTO_INCREMENT=1;
ALTER TABLE Mensaje AUTO_INCREMENT=1;
ALTER TABLE Reclamacion AUTO_INCREMENT=1;